### ISSUE TITLE
关于xml模板

### ISSUE THREAD

**Issue by kafire** [0xa-saline/acunetix-api#1]
https://127.0.0.1:3443/api/v1/report_templates
返回值中并没有template_id为21111111-1111-1111-1111-111111111111    XML
但是
    11111111-1111-1111-1111-111111111111    Developer
    11111111-1111-1111-1111-111111111119    OWASP Top 10 2013 
    11111111-1111-1111-1111-111111111112    Quick
都是有的。
我的AWVS版本号为
Version: 11.0.170951158(5 April 2017)
难道awvs11有多个版本？

**Comment by 0xa-saline** [comment]
Version: 11.0.170951158(5 April 2017) 就这个把.应该都是52pojie的H大神破解的.唔..
21111111-1111-1111-1111-111111111111表示没有压力啊

**Comment by kafire** [comment]
你的博客访问不了了哦，是有新地址了么？
